#!/usr/bin/env zsh

packages=(
    "git" "lazygit" "lazynpm" "lazydocker" "node" "yarn" "npm"
)

if ! command -v brew &>/dev/null; then
    echo "Homebrew not found"
else
    for package in "${packages[@]}"; do
        brew upgrade "${package}"
    done
fi
