#!/usr/bin/env zsh

packages=(
    "onefeatch" "btop" "asciiquarium" "lolcat" "cmatrix" "bat" "fzf"
)

if ! command -v brew &>/dev/null; then
    echo "Homebrew not found"
else
    for package in "${packages[@]}"; do
        brew install "${package}"
    done
fi
