#!/bin/sh

if [ -z "$(which tmux)"]; then
  echo "🥸 Warning, doesn't look like you have Tmux."
fi

if [ -z "$(which vim)"]; then
  echo "🥸 Warning, doesn't look like you have Vim."
fi

exec tmux \
  new-window \;\
  splitw -h \;\
  send vim ENTER \;\
  selectp -t 1 \;\
  splitw \;\
  selectp -t 1 \;\
  resizep -t 2 -y 25 -x 44
