#!/usr/bin/env zsh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [[ -f /etc/lsb-release && "$(grep DISTRIB_ID /etc/lsb-release)" == *Ubuntu* ]]; then
        sudo apt update && sudo apt upgrade -y
    else
        echo "This script only supports Ubuntu and macOS."
        exit 1
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    if ! command -v brew &>/dev/null; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        if [ $? -ne 0 ]; then
            echo "Error installing Homebrew. Please install it manually."
            exit 1
        fi
    fi
    brew update && brew upgrade
else
    echo "This script only supports Ubuntu and macOS."
    exit 1
fi

echo "Update completed."
